apiVersion: v1
kind: Secret
metadata:
  name: banking-db-credentials
  labels:
    app: banking-backend
type: Opaque
stringData:
  DB_HOST: "banking-db.daniyaalabbas-dev.svc.cluster.local"
  DB_USER: "bankadmin"
  DB_PASSWORD: "<CHANGE_IN_OPENSHIFT_SECRETS>"
